export class ProduitImmobilierDTO {



    public static fromJson(json: object): ProduitImmobilierDTO {
        return new ProduitImmobilierDTO(
            json['id'],
            json['type'],
            json['telephone'],
            json['description'],
            json['nbr_lots'],
            !!json['isParking'],
            !!json['isLift'],
            !!json['isGardien'],
            !!json['isCheminee'],
            !!json['isInterphone'],
            !!json['isDigicode'],
            json['orientation'],
            json['dpe'],
            json['etage'],
            json['nbr_piece'],
            json['nbr_chambre'],
            json['nbr_salle_bain'],
            json['nbr_salle_douche'],
            json['nbr_toilette_separe'],
            json['nbr_toilette_non_separe'],
            json['chargesCoprop'],
            json['taxeFonciaire'],
            new Date(json['dateConstruction']),
            new Date(json['dateMiseEnLigne']),
            json['adresse'],
            json['codePostal'],
            json['ville'],
            json['zone'],
            json['prix'],
            json['surface'],
            json['surfaceBalcon'],
            json['surfaceTerrasse'],
            json['surfaceVerandas'],
            json['surfaceSousSol'],
            json['surfaceCave'],
            json['surfaceLogias'],
            json['autreSurfaceAnnexe'],
            json['collectionSize']
        );
    }
    constructor(
        public id: number,
        public type: string,
        public telephone: string,
        public description: string,
        public nbr_lots: number,
        public isParking: boolean,
        public isLift: boolean,
        public isGardien: boolean,
        public isCheminee: boolean,
        public isInterphone: boolean,
        public isDigicode: boolean,
        public orientation: string,
        public dpe: string,
        public etage: number,
        public nbr_piece: number,
        public nbr_chambre: number,
        public nbr_salle_bain: number,
        public nbr_salle_douche: number,
        public nbr_toilette_separe: number,
        public nbr_toilette_non_separe: number,
        public chargesCoprop: number,
        public taxeFonciaire: string,
        public dateConstruction: Date,
        public dateMiseEnLigne: Date,
        public adresse: string,
        public codePostal: string,
        public zone: string,
        public ville: string,
        public prix: number,
        public surface: string,
        public surfaceBalcon: number,
        public surfaceTerrasse: number,
        public surfaceVerandas: number,
        public surfaceSousSol: number,
        public surfaceCave: number,
        public surfaceLogias: number,
        public autreSurfaceAnnexe: number,
        public collectionSize: number) {
    }

 
}
